### ISSUE TITLE
SImGuiOverlay stealing input events from overlapped windows

### ISSUE THREAD

**Issue by mrate** [VesCodes/ImGui#38]
Hello,

We are experiencing an issue with ImGui plugin. If any UE editor window overlaps ImGui widget it won't receive user input. For example - if I have ImGui::Window with a button (or any other widget) somewhere in the Editor viewport and there is some other window opened (for example Message log) then any widget from Message log overlapping any widget from ImGui will not handle input events and those are handle but ImGui instead.

I would say that the problem is in the FImGuiInputProcessor::ShouldHandleEvent() function not properly detecting that there is an overlapping SWindow and in that case it should return false.

**Comment by CA-Jon-Colverson** [comment]
Hello. We're trying out this plugin and are having the same issue. I was wondering if you came up a solution for it that you could share?

**Comment by mrate** [comment]
Hello, I have a working (but a little hacky) solution:

We keep a list of all windows that contain ImGui overlays (SImGuiOverlay). In FImGuiInputProcessor for mouse events we check for given mouse cursor position that there is no overlapping window at that position that does not have an ImGui overlay.

Also since we are using multiple ImGui contexts we keep track of all ImGui windows for each ImGui context. Because there is one FImGuiInputProcessor for each ImGui context we only allow input events for windows that belongs to same ImGui context...

Hope it makes sense :-)

**Comment by CA-Jon-Colverson** [comment]
That's super useful, thank you very much!

**Comment by dyanikoglu** [comment]
I was wondering why my common ui menu inputs stopped working for a while. Turned out this plugin was stealing the input events.

**Comment by VesCodes** [comment]
Hey yall, this should be addressed in https://github.com/VesCodes/ImGui/commit/553df93a6ad07a77556983c9593bef6e807bb8a0 on the `Dev` branch. There's still some quirks that I'd like to dig into eventually but this should address the most egregious behaviour.

Note that the `Dev` branch is using a newer version of ImGui and has the NetImGui integration disabled due to lack of support for some new functionality, so you might need to cherrypick this change into your projects.

**Comment by 1762757171** [comment]
Hi, I've tried the fix. As you said, the issue persists when overlapping with the editor title bar or docked windows (such as the content browser), but the most serious problem when overlapping with other independent windows has been resolved. Looking forward to your further fixes.

**Comment by VesCodes** [comment]
> the issue persists when overlapping with the editor title bar or docked windows (such as the content browser)

@1762757171 I don't think the current setup would allow handling those cases any differently since the main ImGui viewport for PIE is attached to the editor window rather than the game viewport (since that's embedded in the editor window).

I've followed up with a fix for key events that were being erroneously processed for all contexts, and also cherrypicked these fixes into `Main`. Let me know if you bump into any more issues!
